apiVersion: v1
kind: Service
metadata:
  name: spicejetfileparser
  namespace: capiot
spec:
  type: ClusterIP
  selector:
    app: spicejetfileparser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
